#! /usr/bin/sh

# call python cgohlke.py with args
python cgohlke.py "$@"

# check for build log
BUILD_DIR=~/.cgohlke/
BUILD_LOG=${BUILD_DIR}cgohlke.log
if [[ ! -f $BUILD_LOG ]]; then echo > $BUILD_LOG; fi

TEST=

# convert and install packages
if [[ $1 == "install" && -d ${BUILD_DIR} ]]; then
    shift
    for EXE in ${BUILD_DIR}*.exe
    do
        TEST=`grep $EXE $BUILD_LOG`
        echo $TEST
        if [[ $TEST == $EXE ]]
        then
            echo $EXE already converted to wheel!
            TEST=
        else
            echo Converting $EXE to wheel ...
            wheel convert -v $EXE -d ${BUILD_DIR}
            echo $EXE >> $BUILD_LOG
        fi
    done
    pip install --use-wheel --no-index --find-links=${BUILD_DIR} "$@"
fi
