#! /usr/bin/sh

python cgohlke.py "$@"
PATTERN="-[0-9]\+\(\.[0-9]\+\)\+-[cpy0-9]\+-none-\(win32\|any\|win_amd64\).wh
l"

if [[ $1 == "install" && -d ~/.cgohlke ]]
then
    for EXE in ~/.cgohlke/*.exe
    do
        # TODO: check if wheel already exists
        echo converting $EXE to wheel ...
        wheel convert -v $EXE -d ~/.cgohlke
    done
    for WHEEL in ~/.cgohlke/*.whl
    do
        echo installing $WHEEL ...
        pip install $WHEEL
    done
fi